# Analysis of world oil reserves

In [1]:
import requests


# Url for the wiki page containing the data
url = "https://en.wikipedia.org/wiki/Oil_reserves"

response = requests.get(url)

html = response.text

In [2]:
import pandas as pd

df = pd.read_html(html)

df

[    0                                                  1
 0 NaN  The neutrality of this section is disputed. Re...,
     0                                                  1
 0 NaN  This section may require cleanup to meet Wikip...,
                                                     â€”  \
 0                                                   1
 1                                                   2
 2                                                   3
 3                                                   4
 4                                                   5
 5                                                   6
 6                                                   7
 7                                                   8
 8                                                   9
 9                                                  10
 10                                                 11
 11                                                 12
 12                                                 13
 13                                                 14
 14                                                 15
 15                                                 16
 16                                                 17
 17                                                NaN
 18  Notes: 1 Reserve to Production ratio (in years...

                                               Country  \
 0                                           Venezuela
 1                                        Saudi Arabia
 2                                              Canada
 3                                                Iran
 4                                                Iraq
 5                                              Kuwait
 6                                United Arab Emirates
 7                                              Russia
 8                                               Libya
 9                                             Nigeria
 10                                         Kazakhstan
 11                                              Qatar
 12                                              China
 13                                      United States
 14                                             Angola
 15                                            Algeria
 16                                             Brazil
 17                    Total of top seventeen reserves
 18  Notes: 1 Reserve to Production ratio (in years...

                                  Reserves[18] 109 bbl  \
 0                                              302.81
 1                                              267.03
 2                                              175.00
 3                                              155.60
 4                                              145.02
 5                                              101.50
 6                                               97.80
 7                                               80.00
 8                                               48.36
 9                                               36.97
 10                                              30.00
 11                                              25.41
 12                                              25.40
 13                                              25.00
 14                                               8.16
 15                                              12.20
 16                                              13.20
 17                                            1540.43
 18  Notes: 1 Reserve to Production ratio (in years...

                                       Reserves 109 m3  \
 0                                              48.143
 1                                              42.454
 2                                              27.823
 3                                              24.738
 4                                              23.056
 5                                              16.137
 6                                              15.549
 7                                              12.719
 8                                               7.689
 9                                               5.878
 10                                              4.770
 11                                              4.040
 12                                              4.038
 13                                              3.975
 14                                              1.297
 15                                              1.940
 16                                              2.099
 17                                            244.909
 18  Notes: 1 Reserve to Production ratio (in years...

                              Production[19] 106 bbl/d  \
 0                                                 2.1
 1                                                 8.9
 2                                                 2.7
 3                                                 4.1
 4                                                 3.4
 5                                                 2.3
 6                                                 2.4
 7                                                10.0
 8                                                 1.7
 9                                                 2.5
 10                                                1.5
 11                                                1.1
 12                                                4.1
 13                                                7.0
 14                                                1.9
 15                                                1.7
 16                                                2.1
 17                                               59.5
 18  Notes: 1 Reserve to Production ratio (in years...

                                   Production 103 m3/d  \
 0                                                 330
 1                                                1410
 2                                                 430
 3                                                 650
 4                                                 540
 5                                                 370
 6                                                 380
 7                                                1590
 8                                                 270
 9                                                 400
 10                                                240
 11                                                170
 12                                                650
 13                                               1110
 14                                                300
 15                                                270
 16                                                330
 17                                               9460
 18  Notes: 1 Reserve to Production ratio (in years...

     Reserve/ Production Ratio1 years
 0                              387.0
 1                               82.0
 2                              178.0
 3                              101.0
 4                              115.0
 5                               27.0
 6                               18.0
 7                               15.0
 8                               76.0
 9                               41.0
 10                              55.0
 11                              62.0
 12                              17.0
 13                              10.0
 14                              19.0
 15                              15.0
 16                              17.0
 17                              71.0
 18                               NaN  ,
   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vtePeak oil  \
 0                                        Core issues
 1                                  Results/responses
 2                                             People
 3                                              Books
 4                                  Documentary films
 5                                      Organizations
 6                                        Other peaks

   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vtePeak oil.1  \
 0  Peak oil Mitigation of peak oil Predicting the...
 1  Hirsch report Rimini protocol Price of petrole...
 2  Albert Allen Bartlett Colin J. Campbell John M...
 3  The End of Oil The Long Emergency Out of Gas T...
 4  A Crude Awakening Collapse The End of Suburbia...
 5  The Oil Drum Energy Watch Group ODAC OPEC OAPE...
 6  Car Coal Copper Food Gas Gold Minerals Phospho...

    .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vtePeak oil.2
 0                                                NaN
 1                                                NaN
 2                                                NaN
 3                                                NaN
 4                                                NaN
 5                                                NaN
 6                                                NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ]

In [5]:
df[2]

,â€”,Country,Reserves[18] 109 bbl,Reserves 109 m3,Production[19] 106 bbl/d,Production 103 m3/d,Reserve/ Production Ratio1 years
0,1,Venezuela,302.81,48.143,2.1,330,387.0
1,2,Saudi Arabia,267.03,42.454,8.9,1410,82.0
2,3,Canada,175.00,27.823,2.7,430,178.0
3,4,Iran,155.60,24.738,4.1,650,101.0
4,5,Iraq,145.02,23.056,3.4,540,115.0
5,6,Kuwait,101.50,16.137,2.3,370,27.0
6,7,United Arab Emirates,97.80,15.549,2.4,380,18.0
7,8,Russia,80.00,12.719,10.0,1590,15.0
8,9,Libya,48.36,7.689,1.7,270,76.0
9,10,Nigeria,36.97,5.878,2.5,400,41.0
10,11,Kazakhstan,30.00,4.770,1.5,240,55.0
11,12,Qatar,25.41,4.040,1.1,170,62.0
12,13,China,25.40,4.038,4.1,650,17.0
13,14,United States,25.00,3.975,7.0,1110,10.0
14,15,Angola,8.16,1.297,1.9,300,19.0
15,16,Algeria,12.20,1.940,1.7,270,15.0
16,17,Brazil,13.20,2.099,2.1,330,17.0
17,NaN,Total of top seventeen reserves,1540.43,244.909,59.5,9460,71.0
18,Notes: 1 Reserve to Production ratio (in years...,Notes: 1 Reserve to Production ratio (in years...,Notes: 1 Reserve to Production ratio (in years...,Notes: 1 Reserve to Production ratio (in years...,Notes: 1 Reserve to Production ratio (in years...,Notes: 1 Reserve to Production ratio (in years...,NaN

In [8]:
help(data.iloc)

Help on _iLocIndexer in module pandas.core.indexing object:

class _iLocIndexer(_LocationIndexer)
 |  Purely integer-location based indexing for selection by position.
 |
 |  ``.iloc[]`` is primarily integer position based (from ``0`` to
 |  ``length-1`` of the axis), but may also be used with a boolean
 |  array.
 |
 |  Allowed inputs are:
 |
 |  - An integer, e.g. ``5``.
 |  - A list or array of integers, e.g. ``[4, 3, 0]``.
 |  - A slice object with ints, e.g. ``1:7``.
 |  - A boolean array.
 |  - A ``callable`` function with one argument (the calling Series or
 |    DataFrame) and that returns valid output for indexing (one of the above).
 |    This is useful in method chains, when you don't have a reference to the
 |    calling object, but would like to base your selection on some value.
 |
 |  ``.iloc`` will raise ``IndexError`` if a requested indexer is
 |  out-of-bounds, except *slice* indexers which allow out-of-bounds
 |  indexing (this conforms with python/numpy *slice* semantics).
 |
 |  See more at :ref:`Selection by Position <indexing.integer>`.
 |
 |  See Also
 |  --------
 |  DataFrame.iat : Fast integer location scalar accessor.
 |  DataFrame.loc : Purely label-location based indexer for selection by label.
 |  Series.iloc : Purely integer-location based indexing for
 |                 selection by position.
 |
 |  Examples
 |  --------
 |
 |  >>> mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
 |  ...           {'a': 100, 'b': 200, 'c': 300, 'd': 400},
 |  ...           {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000 }]
 |  >>> df = pd.DataFrame(mydict)
 |  >>> df
 |        a     b     c     d
 |  0     1     2     3     4
 |  1   100   200   300   400
 |  2  1000  2000  3000  4000
 |
 |  **Indexing just the rows**
 |
 |  With a scalar integer.
 |
 |  >>> type(df.iloc[0])
 |  <class 'pandas.core.series.Series'>
 |  >>> df.iloc[0]
 |  a    1
 |  b    2
 |  c    3
 |  d    4
 |  Name: 0, dtype: int64
 |
 |  With a list of integers.
 |
 |  >>> df.iloc[[0]]
 |     a  b  c  d
 |  0  1  2  3  4
 |  >>> type(df.iloc[[0]])
 |  <class 'pandas.core.frame.DataFrame'>
 |
 |  >>> df.iloc[[0, 1]]
 |       a    b    c    d
 |  0    1    2    3    4
 |  1  100  200  300  400
 |
 |  With a `slice` object.
 |
 |  >>> df.iloc[:3]
 |        a     b     c     d
 |  0     1     2     3     4
 |  1   100   200   300   400
 |  2  1000  2000  3000  4000
 |
 |  With a boolean mask the same length as the index.
 |
 |  >>> df.iloc[[True, False, True]]
 |        a     b     c     d
 |  0     1     2     3     4
 |  2  1000  2000  3000  4000
 |
 |  With a callable, useful in method chains. The `x` passed
 |  to the ``lambda`` is the DataFrame being sliced. This selects
 |  the rows whose index label even.
 |
 |  >>> df.iloc[lambda x: x.index % 2 == 0]
 |        a     b     c     d
 |  0     1     2     3     4
 |  2  1000  2000  3000  4000
 |
 |  **Indexing both axes**
 |
 |  You can mix the indexer types for the index and columns. Use ``:`` to
 |  select the entire axis.
 |
 |  With scalar integers.
 |
 |  >>> df.iloc[0, 1]
 |  2
 |
 |  With lists of integers.
 |
 |  >>> df.iloc[[0, 2], [1, 3]]
 |        b     d
 |  0     2     4
 |  2  2000  4000
 |
 |  With `slice` objects.
 |
 |  >>> df.iloc[1:3, 0:3]
 |        a     b     c
 |  1   100   200   300
 |  2  1000  2000  3000
 |
 |  With a boolean array whose length matches the columns.
 |
 |  >>> df.iloc[:, [True, False, True, False]]
 |        a     c
 |  0     1     3
 |  1   100   300
 |  2  1000  3000
 |
 |  With a callable function that expects the Series or DataFrame.
 |
 |  >>> df.iloc[:, lambda df: [0, 2]]
 |        a     c
 |  0     1     3
 |  1   100   300
 |  2  1000  3000
 |
 |  Method resolution order:
 |      _iLocIndexer
 |      _LocationIndexer
 |      _NDFrameIndexer
 |      pandas._libs.indexing._NDFrameIndexerBase
 |      builtins.object
 |
 |  Methods inherited from _LocationIndexer:
 |
 |  __getitem__(self, key)
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from _NDFrameIndexer:
 |
 |  __call__(self, axis=None)
 |      Call self as a function.
 |
 |  __setitem__(self, key, value)
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from _NDFrameIndexer:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from _NDFrameIndexer:
 |
 |  __annotations__ = {'_valid_types': <class 'str'>}
 |
 |  axis = None
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pandas._libs.indexing._NDFrameIndexerBase:
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __reduce__ = __reduce_cython__(...)
 |
 |  __setstate__ = __setstate_cython__(...)
 |
 |  ----------------------------------------------------------------------
 |  Static methods inherited from pandas._libs.indexing._NDFrameIndexerBase:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from pandas._libs.indexing._NDFrameIndexerBase:
 |
 |  name
 |
 |  ndim
 |
 |  obj

In [7]:

data = df[2]
data[data.columns[1:]].

,Country,Reserves[18] 109 bbl,Reserves 109 m3,Production[19] 106 bbl/d,Production 103 m3/d,Reserve/ Production Ratio1 years
0,Venezuela,302.81,48.143,2.1,330,387.0
1,Saudi Arabia,267.03,42.454,8.9,1410,82.0
2,Canada,175.00,27.823,2.7,430,178.0
3,Iran,155.60,24.738,4.1,650,101.0
4,Iraq,145.02,23.056,3.4,540,115.0
5,Kuwait,101.50,16.137,2.3,370,27.0
6,United Arab Emirates,97.80,15.549,2.4,380,18.0
7,Russia,80.00,12.719,10.0,1590,15.0
8,Libya,48.36,7.689,1.7,270,76.0
9,Nigeria,36.97,5.878,2.5,400,41.0
10,Kazakhstan,30.00,4.770,1.5,240,55.0
11,Qatar,25.41,4.040,1.1,170,62.0
12,China,25.40,4.038,4.1,650,17.0
13,United States,25.00,3.975,7.0,1110,10.0
14,Angola,8.16,1.297,1.9,300,19.0
15,Algeria,12.20,1.940,1.7,270,15.0
16,Brazil,13.20,2.099,2.1,330,17.0
17,Total of top seventeen reserves,1540.43,244.909,59.5,9460,71.0
18,Notes: 1 Reserve to Production ratio (in years...,Notes: 1 Reserve to Production ratio (in years...,Notes: 1 Reserve to Production ratio (in years...,Notes: 1 Reserve to Production ratio (in years...,Notes: 1 Reserve to Production ratio (in years...,NaN